### PR TITLE
fix #140 add missing tests to select.feature

### LINKED ISSUE #140: Missing tests for select.feature will run into error
# Issue description
~~When running the script 'npm run test:features' then the tests for the select.feature will fail.~~
Vital tests are missing for that feature, namely selectByValue/Attribute/Index/Text using XPath selectors.

# Steps to reproduce
First you need to clone the repo and then npm install and npm install --save-dev cucumber (either version 2.3.1 or latest version 3.0.2, both will work just fine).
```
npm run test:features
```
~~See https://gist.github.com/silkentrance/14827c7d10809fa6ae4d654f6aab9a97 for a log.~~

# Expected behavior
The missing tests should be implemented and run without error.

# Actual behavior
Some of the currently missing tests will run into error.

# Issue occurred on browser/platform 
phantomjs

### PR DESCRIPTION
**Pull request by silkentrance**
# Contribution description
Add missing tests to select.feature
Fix selectOption action

# Pull request checklist
- [x] Contributed code respects the [editorconfig rules](.editorconfig)
- [x] Contributed code passes the [eslint rules](.eslintrc.yaml)
- [x] Contributed code passes the unit tests
- [ ] Added rules are described in the [readme file](README.md)
- [x] [The build](https://travis-ci.org/webdriverio/cucumber-boilerplate) of the PR is passing

### CODE REVIEW

**Comment by silkentrance** [comment]
@christian-bromann Please note that I changed the travis configuration so that

* cucumber@2.3.1 will be installed so that eslint will not fail and 
* we can now use npm run test:features so that the feature are actually being tested

**Comment by silkentrance** [comment]
See failing new tests
https://travis-ci.org/webdriverio/cucumber-boilerplate/jobs/276360593

**Comment by silkentrance** [comment]
Also committing a fix to that problem right now.

**Comment by silkentrance** [comment]
Some more work to do. Existing jests are failing due to change of internal behaviour of selectOption.

**Comment by silkentrance** [comment]
Last build for node v8 failed due to missing eslint package... restart job?

**Comment by silkentrance** [comment]
I have noticed that the latest cucumber@3.0.2 release will also work with cucumber-boilerplate. How about switching to that release?

**Comment by wvankuipers** [comment]
Reverted the Cucumber install (note: named it ESLint in the commit 🤦‍♂️ ) will fix it before releasing 1.3.1. Thanks for the PR @silkentrance

**Pull request merged**
