### PR TITLE
Cucumber v5

### LINKED ISSUE #250: Add support vor Webdriverio v5
# Issue description
> Webdriverio v5 is release, it would be nice to have this repository updated to this version

https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html

### PR DESCRIPTION
**Pull request by abjerstedt**
# Contribution description
This PR is staging for the v5 launch. I have a few more tweaks to make, but the majority of feature files pass, and almost all unit tests pass.

Closes #250

# Pull request checklist
- [X] Contributed code respects the [editorconfig rules](.editorconfig)
- [X] Contributed code passes the [eslint rules](.eslintrc.yaml)
- [x] Contributed code passes the unit tests
- [ ] Added rules are described in the [readme file](README.md)
- [x] [The build](https://travis-ci.org/webdriverio/cucumber-boilerplate) of the PR is passing

### CODE REVIEW

**Comment by abjerstedt** [comment]
This PR is staging for the v5 launch. I have a few more tweaks to make, but the majority of feature files pass, and almost all unit tests pass.

**Comment by mikesalvia** [comment]
@abjerstedt And not at all surprisingly you already did this! LOL

**Comment by itsmepetrov** [comment]
Any updates?

**Comment by christian-bromann** [comment]
Locking conversation until we have updates

**Comment by cbou** [comment]
I have an issue with this branch.

On my laptop everything works fine but on travis I always receive the same error.

`/home/travis/build/webdriver-cucumber/src/steps/given.js:1
(function (exports, require, module, __filename, __dirname) { import { Given } from \'cucumber\';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at loader (/home/travis/build/webdriver-cucumber/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/webdriver-cucumber/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.hookedLoader [as _load] (/home/travis/build/webdriver-cucumber/node_modules/mockery/mockery.js:111:12)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requiredFiles.forEach.codePath (/home/travis/build/webdriver-cucumber/node_modules/@wdio/cucumber-framework/src/index.js:132:13)
    at Array.forEach (<anonymous>)
    at CucumberAdapter.loadSpecFiles (/home/travis/build/webdriver-cucumber/node_modules/@wdio/cucumber-framework/src/index.js:125:30)
    at CucumberAdapter.run (/home/travis/build/webdriver-cucumber/node_modules/@wdio/cucumber-framework/src/index.js:37:18)`

Or if I comment `'./src/steps/given.js'` from `wdio.conf.js` then I get the error from `then.js`.

/home/travis/build/webdriver-cucumber/src/steps/then.js:1
(function (exports, require, module, __filename, __dirname) { import checkClass from \'../support/check/checkClass\';
                                                                     ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at loader (/home/travis/build/webdriver-cucumber/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/webdriver-cucumber/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.hookedLoader [as _load] (/home/travis/build/webdriver-cucumber/node_modules/mockery/mockery.js:111:12)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requiredFiles.forEach.codePath (/home/travis/build/webdriver-cucumber/node_modules/@wdio/cucumber-framework/src/index.js:132:13)
    at Array.forEach (<anonymous>)
    at CucumberAdapter.loadSpecFiles (/home/travis/build/webdriver-cucumber/node_modules/@wdio/cucumber-framework/src/index.js:125:30)
    at CucumberAdapter.run (/home/travis/build/webdriver-cucumber/node_modules/@wdio/cucumber-framework/src/index.js:37:18)

If `given.js`, `then.js` and `when.js` are commented everything works fine again.

I use node v10.12.0 on my laptop and on travis.

**Pull request merged**
