### PR TITLE
check element exists n amount of times

### PR DESCRIPTION
**Pull request by canvaspixels**
Checks that the element is on the page a specific number of times

# Contribution description
> Please add a brief description of the contents of the pull request

# Pull request checklist
- [ ] Contributed code respects the [editorconfig rules](.editorconfig)
- [ ] Contributed code passes the [eslint rules](.eslintrc.yaml)
- [ ] Contributed code passes the unit tests
- [ ] Added rules are described in the [readme file](README.md)
- [ ] [The build](https://travis-ci.org/webdriverio/cucumber-boilerplate) of the PR is passing

### CODE REVIEW

**Comment by wvankuipers** [comment]
Thanks for the PR @canvaspixels, if you would sign the [Contributor License Agreement](https://cla.js.foundation/webdriverio/cucumber-boilerplate?pullRequest=137) we would be more than happy to merge this into the repository!

**Comment by canvaspixels** [comment]
I've signed that now @wvankuipers cheers

**Comment by christian-bromann** [comment]
@canvaspixels thanks! I think the tests are failing due to old issues, do you mind fetching the latest from master branch and rebase your stuff on top of it?

**Comment by canvaspixels** [comment]
Will do, is there not an error on the current build though? That's what the widget says on the readme page https://github.com/webdriverio/cucumber-boilerplate

**Comment by wvankuipers** [comment]
@canvaspixels That widget is for the build of the master branch, this pr has it's own tests see the "Some checks where not successful" section below and click "Show all checks"  (or click [here](https://travis-ci.org/webdriverio/cucumber-boilerplate/builds/275245689?utm_source=github_status&utm_medium=notification))

**Comment by canvaspixels** [comment]
@wvankuipers all passing! 💪

**Comment by wvankuipers** [comment]
Thanks @canvaspixels

**Pull request merged**
