### PR TITLE
Fix shard artifact upload

### PR DESCRIPTION
**Pull request by WilliamFClarke**
# Contribution description
This fixes the failed artifact upload that happens because the name contains a "/" and replaces it with "-"

# Pull request checklist
- [✔️] Contributed code respects the [editorconfig rules](.editorconfig)
- [✔️] Contributed code passes the [eslint rules](.eslintrc.yaml)
- [✔️] Added rules are described in the [readme file](README.md)

### CODE REVIEW

**Comment by christian-bromann** [comment]
It seems like the command fails:

```
Run SHARD_NAME=$(echo "3/4" | sed 's/\//\-/g')
  SHARD_NAME=$(echo "3/4" | sed 's/\//\-/g')
  echo "::set-output name=shard_name::$SHARD_NAME"
  id: replace_slashes
  shell: /usr/bin/bash -e {0}
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[2](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:2)022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
/home/runner/work/_temp/e79d[3](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:3)[4](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:4)9a-8447-4f[5](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:5)5-8ef7-[6](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:7)6952e9c[7](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:8)cdc.sh: line 3: id:: command not found
Error: Process completed with exit code 127.
```

**Comment by christian-bromann** [comment]
Instead of tweaking the shard name, how about: https://github.com/webdriverio/cucumber-boilerplate/commit/8a7e2a756d23091944b75a53a47916d53df5448b

**Comment by WilliamFClarke** [comment]
> It seems like the command fails:
> 
> ```
> Run SHARD_NAME=$(echo "3/4" | sed 's/\//\-/g')
>   SHARD_NAME=$(echo "3/4" | sed 's/\//\-/g')
>   echo "::set-output name=shard_name::$SHARD_NAME"
>   id: replace_slashes
>   shell: /usr/bin/bash -e {0}
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[2](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:2)022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> /home/runner/work/_temp/e79d[3](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:3)[4](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:4)9a-8447-4f[5](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:5)5-8ef7-[6](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:7)6952e9c[7](https://github.com/webdriverio/cucumber-boilerplate/actions/runs/6878893548/job/18712169216?pr=911#step:5:8)cdc.sh: line 3: id:: command not found
> Error: Process completed with exit code 127.
> ```

Yes this approach was not working and set-output is deprecated.
I have added a new approach which is working in my fork. I instead create a new environment variable called  SHARD_NAME.

**Comment by christian-bromann** [comment]
@WilliamFClarke what do you think about my suggestion?

**Comment by WilliamFClarke** [comment]
> @WilliamFClarke what do you think about my suggestion?

I think your suggestion is a better approach so I will close this PR.

**Pull request closed without merging**
