### PR TITLE
Updated dependencies in package.json

### PR DESCRIPTION
**Pull request by wvankuipers**
Updated dependencies and ran all the tests

### CODE REVIEW

**Comment by wvankuipers** [comment]
@christian-bromann I updated the dependencies, looks good @ my end!

I notice the builds are currently not running any tests?
Maybe you could hook up a sauce labs account so the test can be ran there?

**Comment by wvankuipers** [comment]
@christian-bromann I updated all the rules to match the new WebdriverIO promise structure.
Executed all tests an d all seems to be fine.

Coul you look into accepting this? I have a bunch of extra rules to add to this project, but they depend on the upgraded dependencies.

**Comment by christian-bromann** [comment]
@wvankuipers That looks awesome! Two things:

- could you rebase your branch with current master?
- what happen if you let a step fail? Does it report properly?

**Comment by wvankuipers** [comment]
Rebase is done, test result for failing test:

     Github test
    open URL
      ✓ Given I open the url "https://github.com/" (1663ms)
      1) Then  I expect that the url is "https://this-is-not.github.com/"
      - And   I expect that the title is "GitHub · Where software is built"

      Github test
        open URL
          ✓ Given I open the url "https://github.com/webdriverio/cucumber-boilerplate" (679ms)
          ✓ Then  I expect that element ".octicon-mark-github" does exist
          ✓ And I expect that element ".some-other-element" does not exist


      4 passing (4s)
      1 pending
      1 failing

      1) Github test open URL Then  I expect that the url is "https://this-is-not.github.com/":

          Uncaught undefined: expected url to be "https://this-is-not.github.com/"  but found "https://github.com/": expected 'https://github.com/' to equal 'https://this-is-not.github.com/'
          + expected - actual

          -https://github.com/
          +https://this-is-not.github.com/

          at url("https://github.com/") - given.js:9:26

**Comment by christian-bromann** [comment]
Looking good! Thanks!

**Pull request merged**
