### PR TITLE
Adding @isolate tag

### PR DESCRIPTION
**Pull request by obsidianart**
Adding the possibility to isolate single or multiple scenarios

### CODE REVIEW

**Comment by christian-bromann** [comment]
@obsidianart how about calling the tag `@Only` to be more consistent with the Mocha framework?

**Comment by obsidianart** [comment]
Well, @Only already run only the isolated test?! The main difference is that @Only ignore every other test and run only the last marked foound.
I have no idea why @Only already works but it would be nice to document it.
I changed my code to work with Only or Isolate, whatever you want to isolate a single test or a bunch of them.
I'll let it up to you to implement both features or not (personally I often Isolate 2 or 3 tests per time.

**Comment by christian-bromann** [comment]
Thanks @obsidianart

**Comment by christian-bromann** [comment]
I guess __@Only__ works as it is part of the yadda framework

**Pull request merged**
