### PR TITLE
Added check title contains

### PR DESCRIPTION
**Pull request by amarnathk1547**
# Contribution description
> Please add a brief description of the contents of the pull request
Added checkTitleContains() to help in matching partial titles as well
# Pull request checklist
- [x] Contributed code respects the [editorconfig rules](.editorconfig)
- [x] Contributed code passes the [eslint rules](.eslintrc.yaml)
- [ ] Contributed code passes the unit tests
- [x] Added rules are described in the [readme file](README.md)
- [x] [The build](https://travis-ci.org/webdriverio/cucumber-boilerplate) of the PR is passing

### CODE REVIEW

**Comment by christian-bromann** [comment]
Step definition for this is missing. Also not sure how useful this is since not many people check their page url.

**Comment by amarnathk1547** [comment]
Added step definitions in next PR. Checking titles either partially or exactly would help in validating navigation between different pages. Hope it will help others

**Comment by christian-bromann** [comment]
> Added step definitions in next PR.

Let's have it all in this one

**Comment by amarnathk1547** [comment]
Done!

**Pull request merged**
