### PR TITLE
Separate commands to improve Windows compatibility

### PR DESCRIPTION
**Pull request by alexcason**
Discussed in #31.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@alexcason this seems to break the build

```
  1) Test the attributes of a given element "before all" hook:
     Uncaught Error: Couldn't connect to selenium server
```

Could you take a look?

**Comment by alexcason** [comment]
@christian-bromann Sure, let me take a look.

**Comment by alexcason** [comment]
@christian-bromann Should be fixed now. Just needed to update the travis build script to use the new server commands.

**Comment by christian-bromann** [comment]
Sweet, looks good!

**Pull request merged**
