### PR TITLE
test:validate not working on clone

### PR DESCRIPTION
**Pull request by computamike**
# Contribution description
> When cloning the repository - it was unable to run test:validate as the code failed the eslinting tests, and threw a deprecation warning.  I ran eslint with --fix, and am checking in those changes, and suggest that reverting to eslint v 4.19.1 removes this deprecation warning.  This is probably more a problem with the airbnb-base code.  Will look at fixing it there also.

**Note for webdriverio maintainers:** 
I wasn't sure what the policy was in terms of the test:validate throwing deprecation warnings.  By downgrading the eslint 4.19.1 I was able to remove the feature causing the deprecation warning - however I would understand if the decision was made to reject this, as there could be an argument that the fix should be applied at the airbnb-base package. If you need me to revert that part let me know and I'll just push the code layout changes.

# Pull request checklist
- [X] Contributed code respects the [editorconfig rules](.editorconfig)
- [X] Contributed code passes the [eslint rules](.eslintrc.yaml)
- [X] Contributed code passes the unit tests
- [X] Added rules are described in the [readme file](README.md)
- [ ] [The build](https://travis-ci.org/webdriverio/cucumber-boilerplate) of the PR is passing

### CODE REVIEW

**Comment by computamike** [comment]
webdriverio maintainers : I note that the CodeClimate failure is based on the changes made by myself.  Checking the code using eslint locally this file is fine and produces no error - however, codeClimate throws an error.  Please advise best course of action -

**Comment by computamike** [comment]
have found this might be due to a mismatch in eslint version - CodeClimate uses 4.15 of eslint - whereas I have been testing with 4.19.1.  Will refix errors using 4.15 eslint so that codeClimate will operate sucessfully.

**Comment by christian-bromann** [comment]
I am not sure how I feel about downgrading eslint. Can't we fix the issue we have with latest version?

**Comment by computamike** [comment]
@christian-bromann : I think it should be possible - but CodeClimate is currently running version 4.19.1 - so how do we reconcile the differences between the versions of eslint running on a developer's machine (as installed through package.json) and the eslint dependancy set up in codeclimate.yml.

If we leave these versions of eslint different, then it might be possible for a user to perform test:validate locally - have it pass, but when it is run through codeClimate it fails the tests.

**Comment by computamike** [comment]
https://docs.codeclimate.com/docs/eslint 

Language / Framework: JavaScript
Checks: 190+
Categories: Complexity, Style
Channels: stable: ESLint v3.19.0, eslint-1: ESLint v1.10.3, eslint-2: ESLint v2.10.2, eslint-4: ESLint **v4.15.0**

**Comment by computamike** [comment]
@christian-bromann  - I would also point out that issuing a ```npm install``` presents the following warnings : 

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-airbnb-base@13.0.0 requires a peer of eslint@^4.19.1 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

Note that eslint-config-airbnb-nase has a peer dependancy of eslint 4.19.1 - whereas package.json installs 5.0.0

**Comment by christian-bromann** [comment]
@computamike how do we want to move forward?

**Comment by computamike** [comment]
@christian-bromann - I'm going to close this pull request - I think I can do better, and I think we can potentially fix without the downgrade -

**Pull request closed without merging**
