### PR TITLE
Feature/new rules

### PR DESCRIPTION
**Pull request by wvankuipers**
**Note** this PR depends on #25 & #26

This PR features quite a few things;
- Added > 80 rules
- Switched to [selenium-standalone](https://www.npmjs.com/package/selenium-standalone)
- Added loads of feature tests
- Added a demo-app to run the feature test on
- Fixed a few minor issues & rewrote some of the existing rules

It is basically a massive rewrite/update of the boilerplate that implements more general tests and examples on how to implement them. Maybe this is the time to implement a version number for this project so it's clear what version a project is using?

:christmas_tree: :santa: :gift: Merry Christmas

### CODE REVIEW

**Comment by christian-bromann** [comment]
This is fantastic. Thanks so much!
Seems that the build is failing due to a selenium-webdriver install issue:

```
-----
selenium-standalone installation finished
-----
/home/travis/build/webdriverio/cucumber-boilerplate/node_modules/selenium-standalone/lib/install.js:248
  fs.access(where, fs.R_OK | fs.X_OK, function(err) {
     ^
TypeError: Object #<Object> has no method 'access'
```

I am happy to merge this if we can get a green build. Would this make #25 and #26 obsolete?

**Comment by wvankuipers** [comment]
Ok it's getting stuck on the ChromeDriver (can't spawn a Chrome browser in Travis) 

Gonne integrate a build test run using PhantomJS, will update this PR when it's done.

**Comment by wvankuipers** [comment]
Ok all done! Had to disable Some tests benauwd they failed om PhantomJs but THE build noe passes 😎

**Comment by christian-bromann** [comment]
> Gonne integrate a build test run using PhantomJS, will update this PR when it's done.

I think phantomjs tests are sufficient here. We already test command across multiple commands in the WebdriverIO test suite. No need to do it here too.

Thanks so much. This is really great. I will probably reuse all these preconfigured steps when I work on the cucumber adapter for the wdio test runner.

Awesome christmas present for sure!

**Pull request merged**
